(()=>{'use strict';
const SUPABASE_URL='https://qgmpwanxqytoakmnklvy.supabase.co';const SUPABASE_KEY='sb_publishable_qlOg73Ee92_uzX9YsaRPIA_dMQX9gub';const BUCKET='B. Pharm Notes';const $=id=>document.getElementById(id);let client=null;
const SUBJECTS={
'1st Semester':['Human Anatomy and Physiology I','Pharmaceutical Analysis I','Pharmaceutics I','Pharmaceutical Inorganic Chemistry','Communication Skills','Remedial Biology / Remedial Mathematics'],
'2nd Semester':['Human Anatomy and Physiology II','Pharmaceutical Organic Chemistry I','Biochemistry','Pathophysiology','Computer Applications in Pharmacy','Environmental Sciences'],
'3rd Semester':['Pharmaceutical Organic Chemistry II','Physical Pharmaceutics I','Pharmaceutical Microbiology','Pharmaceutical Engineering'],
'4th Semester':['Pharmaceutical Organic Chemistry III','Medicinal Chemistry I','Physical Pharmaceutics II','Pharmacology I','Pharmacognosy and Phytochemistry I'],
'5th Semester':['Medicinal Chemistry II','Industrial Pharmacy I','Pharmacology II','Pharmacognosy and Phytochemistry II','Pharmaceutical Jurisprudence'],
'6th Semester':['Medicinal Chemistry III','Pharmacology III','Herbal Drug Technology','Biopharmaceutics and Pharmacokinetics','Pharmaceutical Biotechnology','Quality Assurance'],
'7th Semester':['Instrumental Methods of Analysis','Industrial Pharmacy II','Pharmacy Practice','Novel Drug Delivery System'],
'8th Semester':['Biostatistics and Research Methodology','Social and Preventive Pharmacy','Pharma Marketing Management','Pharmaceutical Regulatory Science','Pharmacovigilance','Quality Control and Standardization of Herbals','Computer Aided Drug Design','Cell and Molecular Biology','Cosmetic Science','Experimental Pharmacology','Advanced Instrumentation Techniques','Dietary Supplements and Nutraceuticals','Project Work']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const msg=(el,t,ok=false)=>{if(!el)return;el.textContent=t||'';el.className='message '+(ok?'ok':'error')};
async function isAdmin(uid){const {data,error}=await client.from('admin_users').select('user_id').eq('user_id',uid).maybeSingle();if(error)throw error;return!!data}
async function showSession(){try{const {data,error}=await client.auth.getSession();if(error)throw error;const s=data.session;if(!s){$('loginView').classList.remove('hidden');$('adminView').classList.add('hidden');return}if(!(await isAdmin(s.user.id))){await client.auth.signOut();$('loginView').classList.remove('hidden');$('adminView').classList.add('hidden');msg($('loginMsg'),'This account is not authorized as an admin.');return}$('userEmail').textContent=s.user.email||'';$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden');await loadNotes();await loadIndustry()}catch(e){console.error(e);msg($('loginMsg'),e.message||'Session check failed.')}}
async function login(e){e.preventDefault();msg($('loginMsg'),'Signing in…',true);try{const {error}=await client.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;await showSession()}catch(e){console.error(e);msg($('loginMsg'),e.message||'Sign-in failed.')}}async function logout(){await client.auth.signOut();await showSession()}
function safeName(n){return n.replace(/\.pdf$/i,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'file'}function publicPath(url){try{const marker=`/storage/v1/object/public/${encodeURIComponent(BUCKET)}/`;if(url&&url.includes(marker))return decodeURIComponent(url.split(marker)[1]);const raw=`/storage/v1/object/public/${BUCKET}/`;if(url&&url.includes(raw))return decodeURIComponent(url.split(raw)[1])}catch(e){}return null}
async function uploadFile(file,folder){const path=`${folder}/${Date.now()}-${safeName(file.name)}.pdf`;const {error}=await client.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',cacheControl:'3600',upsert:false});if(error)throw error;return{path,url:client.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}}
function populateSubjects(){const sem=$('semester').value,sub=$('subject'),unit=$('unit');sub.innerHTML='<option value="">Select subject</option>';unit.innerHTML='<option value="">Select subject first</option>';unit.disabled=true;sub.disabled=!sem;if(sem)(SUBJECTS[sem]||[]).forEach(x=>sub.insertAdjacentHTML('beforeend',`<option>${esc(x)}</option>`))}
function populateUnits(){const sub=$('subject').value,unit=$('unit');unit.innerHTML='<option value="">Select unit</option>';unit.disabled=!sub;if(sub){for(let i=1;i<=5;i++)unit.insertAdjacentHTML('beforeend',`<option>Unit ${i}</option>`);unit.insertAdjacentHTML('beforeend','<option>All Units / Complete Notes</option>')}}
async function uploadNote(e){e.preventDefault();const file=$('pdf').files[0];if(!file)return msg($('uploadMsg'),'Choose a PDF first.');if(file.size>25*1024*1024)return msg($('uploadMsg'),'PDF must be 25 MB or smaller.');msg($('uploadMsg'),'Uploading…',true);let path=null;try{const r=await uploadFile(file,'notes');path=r.path;const payload={title:$('title').value.trim(),semester:$('semester').value,subject:$('subject').value.trim(),unit:$('unit').value,description:$('description').value.trim(),pdf_url:r.url};const {error}=await client.from('notes').insert(payload);if(error)throw error;$('uploadForm').reset();populateSubjects();$('fileName').textContent='No file selected';msg($('uploadMsg'),'Note published successfully.',true);await loadNotes()}catch(e){if(path)await client.storage.from(BUCKET).remove([path]);console.error(e);msg($('uploadMsg'),e.message||'Upload failed.')}}
async function uploadIndustry(e){e.preventDefault();const file=$('industryPdf').files[0];if(file&&file.size>25*1024*1024)return msg($('industryMsg'),'PDF must be 25 MB or smaller.');msg($('industryMsg'),'Publishing…',true);let path=null;try{let url=null;if(file){const r=await uploadFile(file,'industry');path=r.path;url=r.url}const {error}=await client.from('industry_resources').insert({title:$('industryTitle').value.trim(),category:$('industryCategory').value,description:$('industryDescription').value.trim(),pdf_url:url});if(error)throw error;$('industryForm').reset();$('industryFileName').textContent='No PDF selected';msg($('industryMsg'),'Industry resource published successfully.',true);await loadIndustry()}catch(e){if(path)await client.storage.from(BUCKET).remove([path]);console.error(e);msg($('industryMsg'),e.message||'Publish failed.')}}
async function loadNotes(){const box=$('notesList');box.innerHTML='<p class="muted">Loading…</p>';const {data,error}=await client.from('notes').select('*').order('created_at',{ascending:false});if(error){box.innerHTML=`<p class="message error">${esc(error.message)}</p>`;return}if(!data?.length){box.innerHTML='<p class="muted">No notes published yet.</p>';return}box.innerHTML=data.map(n=>`<article class="note-row"><div><span class="badge">${esc(n.semester)}</span><h3>${esc(n.title)}</h3><p><strong>${esc(n.subject)}</strong>${n.unit?' · '+esc(n.unit):''}${n.description?' · '+esc(n.description):''}</p></div><div class="row-actions"><a class="btn" href="${esc(n.pdf_url)}" target="_blank" rel="noopener">View</a><button class="btn danger" data-del="${esc(n.id)}" data-url="${esc(n.pdf_url)}">Delete</button></div></article>`).join('');box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteNote(b.dataset.del,b.dataset.url))}
async function loadIndustry(){const box=$('industryList');box.innerHTML='<p class="muted">Loading…</p>';const {data,error}=await client.from('industry_resources').select('*').order('created_at',{ascending:false});if(error){box.innerHTML=`<p class="message error">${esc(error.message)}</p>`;return}if(!data?.length){box.innerHTML='<p class="muted">No industry resources published yet.</p>';return}box.innerHTML=data.map(n=>`<article class="note-row"><div><span class="badge">${esc(n.category)}</span><h3>${esc(n.title)}</h3><p>${esc(n.description||'')}</p></div><div class="row-actions">${n.pdf_url?`<a class="btn" href="${esc(n.pdf_url)}" target="_blank" rel="noopener">View PDF</a>`:''}<button class="btn danger" data-ind="${esc(n.id)}" data-url="${esc(n.pdf_url||'')}">Delete</button></div></article>`).join('');box.querySelectorAll('[data-ind]').forEach(b=>b.onclick=()=>deleteIndustry(b.dataset.ind,b.dataset.url))}
async function deleteNote(id,url){if(!confirm('Delete this note?'))return;try{const p=publicPath(url);if(p)await client.storage.from(BUCKET).remove([p]);const {error}=await client.from('notes').delete().eq('id',id);if(error)throw error;await loadNotes()}catch(e){alert(e.message||'Delete failed.')}}async function deleteIndustry(id,url){if(!confirm('Delete this industry resource?'))return;try{const p=publicPath(url);if(p)await client.storage.from(BUCKET).remove([p]);const {error}=await client.from('industry_resources').delete().eq('id',id);if(error)throw error;await loadIndustry()}catch(e){alert(e.message||'Delete failed.')}}
function bind(){$('loginForm').onsubmit=login;$('logoutBtn').onclick=logout;$('uploadForm').onsubmit=uploadNote;$('industryForm').onsubmit=uploadIndustry;$('refreshBtn').onclick=loadNotes;$('industryRefreshBtn').onclick=loadIndustry;$('semester').onchange=populateSubjects;$('subject').onchange=populateUnits;$('pdf').onchange=()=>{$('fileName').textContent=$('pdf').files[0]?.name||'No file selected'};$('industryPdf').onchange=()=>{$('industryFileName').textContent=$('industryPdf').files[0]?.name||'No PDF selected'};$('notesTab').onclick=()=>{ $('notesTab').classList.add('active');$('industryTab').classList.remove('active');$('notesPanel').classList.remove('hidden');$('industryPanel').classList.add('hidden')};$('industryTab').onclick=()=>{ $('industryTab').classList.add('active');$('notesTab').classList.remove('active');$('industryPanel').classList.remove('hidden');$('notesPanel').classList.add('hidden')}}
function init(){if(!window.supabase?.createClient){msg($('loginMsg'),'Supabase library load nahi hui. Refresh karke dobara try karein.');return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);bind();showSession()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()})();