-- Pharma Industry content table + admin RLS
create table if not exists public.industry_content (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text,
  pdf_url text,
  created_at timestamptz default now()
);

alter table public.industry_content enable row level security;

grant select on public.industry_content to anon;
grant select, insert, update, delete on public.industry_content to authenticated;

drop policy if exists "Public can read industry content" on public.industry_content;
create policy "Public can read industry content"
on public.industry_content
for select to anon, authenticated
using (true);

drop policy if exists "Admins can insert industry content" on public.industry_content;
create policy "Admins can insert industry content"
on public.industry_content
for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update industry content" on public.industry_content;
create policy "Admins can update industry content"
on public.industry_content
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete industry content" on public.industry_content;
create policy "Admins can delete industry content"
on public.industry_content
for delete to authenticated
using (public.is_admin());

-- Reuse the existing public bucket: PDFs are stored under the industry/ prefix.
drop policy if exists "Admins can upload industry files" on storage.objects;
create policy "Admins can upload industry files"
on storage.objects
for insert to authenticated
with check (
  bucket_id = 'B. Pharm Notes'
  and name like 'industry/%'
  and public.is_admin()
);

drop policy if exists "Admins can update industry files" on storage.objects;
create policy "Admins can update industry files"
on storage.objects
for update to authenticated
using (
  bucket_id = 'B. Pharm Notes'
  and name like 'industry/%'
  and public.is_admin()
)
with check (
  bucket_id = 'B. Pharm Notes'
  and name like 'industry/%'
  and public.is_admin()
);

drop policy if exists "Admins can delete industry files" on storage.objects;
create policy "Admins can delete industry files"
on storage.objects
for delete to authenticated
using (
  bucket_id = 'B. Pharm Notes'
  and name like 'industry/%'
  and public.is_admin()
);
