-- Pharmistry World: B.Pharm notes hierarchy migration + Industry table compatibility
alter table public.notes add column if not exists unit text;
create index if not exists notes_semester_subject_unit_idx on public.notes(semester, subject, unit);

-- The admin panel uses this table for Pharma Industry resources.
create table if not exists public.industry_resources (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text,
  pdf_url text,
  created_at timestamptz default now()
);
alter table public.industry_resources enable row level security;
drop policy if exists "Anyone can view industry resources" on public.industry_resources;
create policy "Anyone can view industry resources" on public.industry_resources for select to anon, authenticated using (true);
drop policy if exists "Admins can insert industry resources" on public.industry_resources;
create policy "Admins can insert industry resources" on public.industry_resources for insert to authenticated with check (public.is_admin());
drop policy if exists "Admins can update industry resources" on public.industry_resources;
create policy "Admins can update industry resources" on public.industry_resources for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins can delete industry resources" on public.industry_resources;
create policy "Admins can delete industry resources" on public.industry_resources for delete to authenticated using (public.is_admin());
grant select on public.industry_resources to anon;
grant select, insert, update, delete on public.industry_resources to authenticated;

-- Normalize older semester values already in the table.
update public.notes set semester='1st Semester' where lower(trim(semester)) in ('1st','1st semester');
update public.notes set semester='2nd Semester' where lower(trim(semester)) in ('2nd','2nd semester');
update public.notes set semester='3rd Semester' where lower(trim(semester)) in ('3rd','3rd semester');
update public.notes set semester='4th Semester' where lower(trim(semester)) in ('4th','4th semester');
update public.notes set semester='5th Semester' where lower(trim(semester)) in ('5th','5th semester');
update public.notes set semester='6th Semester' where lower(trim(semester)) in ('6th','6th semester');
update public.notes set semester='7th Semester' where lower(trim(semester)) in ('7th','7th semester');
update public.notes set semester='8th Semester' where lower(trim(semester)) in ('8th','8th semester');
