-- Run once in Supabase SQL Editor. Never expose a service_role/secret key.
create table if not exists public.notes(id bigint generated by default as identity primary key,title text not null,semester text not null,subject text not null,description text,pdf_url text not null,created_at timestamptz default now());
alter table public.notes enable row level security;
grant select on public.notes to anon, authenticated;
drop policy if exists "Public can read notes" on public.notes;
create policy "Public can read notes" on public.notes for select to anon,authenticated using(true);
drop policy if exists "Authenticated can publish notes" on public.notes;
create policy "Authenticated can publish notes" on public.notes for insert to authenticated with check(true);
drop policy if exists "Authenticated upload pharma notes" on storage.objects;
create policy "Authenticated upload pharma notes" on storage.objects for insert to authenticated with check(bucket_id='B. Pharm Notes');
